### ISSUE TITLE
HEVC Error Accumulation in Stream

### ISSUE THREAD

**Issue by TechWendigo** [TheElixZammuto/moonlight-xbox#190]
**Describe the bug**
When using HEVC as the decoder on Xbox any still elements on screen eventually start to accumulate errors and those errors compound on top of each other and spread onto other elements until something high contrast moves through the artifacts and "cleans" it temporarily.

**To Reproduce**
1. AMD host PC using the AMF encoder set to advertise HEVC support
2. Set Xbox to use HEVC (it forces it in most cases regardless of setting)
3. Put almost any content on screen and wait

**Screenshots or Videos**

![Image](https://github.com/user-attachments/assets/c9f82c19-ca2b-457d-a4cf-996fd677f976)

Logs looked normal I can reproduce with them if needed.

**Guest Information:**
 - Xbox Model: [Xbox Series X]
 - TV Resolution: [4K SDR, HDR]

**Host Information**
- Operating System: [Windows]
- Host Software: [Sunshine]
- Monitor Resolutions [4K]

**Additional context**
I heard Nvidia users on Apollo can use Intra Refresh to mitigate this but I cannot confirm I use Radeon.

**Comment by Santoz2** [comment]
+1 for this issue. In my case, so far it hasn't been a major problem since it only shows up when things are stationary for a while. For example, when taking too long in Clair Obscur's skill menus:

![Image](https://github.com/user-attachments/assets/c9e54429-bbff-468f-ae76-3e4699059ec6)

Setup: AMD Radeon RX 9070XT GPU, Ryzen 7 9800x3d CPU, Streamed to Xbox Series X

Original NVIDIA issue was fixed in [Issue 117](https://github.com/TheElixZammuto/moonlight-xbox/issues/117) , would be great to hear of an AMD solution as well.

Love this project btw, streaming 4k 60 from my PC to the tv instead of dragging an hdmi cable across my apartment is a huge upgrade!

**Comment by TaoRS** [comment]
I'm still having this issue.

Host:
- cachyos 
- RTX 4070

Client
- 4k
- 60fps

Only happens on my Xbox, my steam deck works just fine

**Comment by bennyb0i** [comment]
I'm having this issue too. Artifacts start accumulating on relatively static areas of the screen after 5-10 minutes and then spread to pretty much the entire screen after a short while. A disconnect/reconnect of the stream temporarily fixes things, but like clockwork the artifacts return after 5-10 minutes of gameplay.

Host:

- Arch Linux
- RTX 4070Ti
- Sunshine stable latest (also tried nightly)

Client:

- Xbox Series X
- Moonlight UWP 1.18.0.70
- HEVC
- 1440p
- 120 Hz (also tried 60 Hz)
- Immediate frame pacing (also tried synced with display)

**Comment by rrodriguez81** [comment]
First of all, thanks for you great work, is really really good. Congratulations.

I’ve got the same problem, also I’ve got an AMD host using the AMF. It succeed when I don’t move the image with the controller for some seconds.

Guest Information:

Xbox Model: [Xbox Series S]
TV Resolution: [4K 60Hz SDR, HDR]

Host Information:

Operating System: [Windows]
Host Software: [Sunshine]
Monitor Resolutions [4K] 


Not sure if helps, or if it’s related, but if I set a very high bandwith (300Mbps), when I don’t touch the control or move the  sticks, after a few seconds I start receiveing lots of network errors and the image start to skip frames. It’s not a bandwith problem because when I’m moving is almost perfect, but it suceed aswell when I don’t move the sticks ( not sure if related with the same issue )

**Comment by solidv** [comment]
I have this issue too.

Host:
Sunshine nightly arch linux
9070XT

Client:
Xbox Series S

**Comment by razorlikes** [comment]
Same here, 9070 XT streaming to a Series S from Windows, 4k120 SDR using H265. 

On a side note, the codec selection on Xbox doesn't seem to do anything? I can only get Moonlight to use H264 instead of H265 if I force it through Sunshine/Apollo and set the resolution to 1080p in Moonlight. At 1440p or 4K Moonlight just crashes if I force H264.

**Comment by TechWendigo** [comment]
@razorlikes The Xbox's H.264 decoder is set to a maximum of 1080p 120hz and will not decode above that. It will force HEVC if it detects 1440p and 2160p sources.

**Comment by CerebroDOW** [comment]
Also experiencing this issue. Some games are worse than others. Though most exhibit regardless of the title being played. Exception found is RE9 Requiem which I believe is because of the forced post processing film grain setting that you can not disable without messing with .ini files. (Just a theory).

HOST:
Vibepollo (1.15.1) Host on Windows 11
Ryzen 7 5700X3D
RX 9070
2.5gbe wired connection 

CLIENT:
Xbox Series S
4K @120FPS (SDR without VRR)
1gbe wired connection

**Comment by xxvertigoxx** [comment]
Same issue here, definitely happens more with some games than others. The more visually complex/demanding the game is the more it seems to happen. BG3 is absolutely terrible for it, conversations with NPCs will often force me to restart the xbox.

Host Information:
Operating System: Arch Linux
GPU: 4080 Super
Host Software: Sunshine Version 2025.924.154138 (latest stable)
Monitor Resolutions: 1440p

Guest Information:
Xbox Model: Xbox Series X
TV Resolution: 1440p 60Hz SDR

**Comment by fama-lama** [comment]
Experience same issue in RDR2.
