### ISSUE TITLE
1/4 of desktop streamed

### ISSUE THREAD

**Issue by ReenigneArcher** [TheElixZammuto/moonlight-xbox#20]
With latest release, 1.8.10.70 (retail)

Only the top left 1/4 of the desktop is streamed to the client app.

Host: Win 10 Pro with GeForce Experience (1080p? dummy hdmi dongle)
Client: Xbox One X (4k TV)

Settings:
1080p, 60 FPS

**Comment by ip0p** [comment]
had you old versions installed already installed before? I had this issue in old version and after completley reinstalling the app this was gone.

**Comment by ReenigneArcher** [comment]
> had you old versions already installed before? I had this issue in old version and after completley reinstalling the app this was gone.

Yes I have 1.8.9.70. I will give it a try. Thanks!

**Comment by joaopedrosgs** [comment]
I have the exact same problem and reinstalling didn't work

**Comment by MrThista** [comment]
I have same issue too, 
![16434005780414224988036511424612](https://user-images.githubusercontent.com/26851101/151614616-17ff6389-a6e6-4a09-91bb-2544346514cb.jpg)

**Comment by TheElixZammuto** [comment]
Hi, 
What happens when the TV resolution is changed?
Personally I had this issue too but I managed to uninstall/reinstall to make it work successfully

**Comment by Ebloin** [comment]
Same issue for me on Xbox Series S with last retail Version 1.8.10.70.
I also tried to uninstall completely and reinstall but didn't solve.
Xbox is connected to an LG 4k TV.

**Comment by ReenigneArcher** [comment]
> Hi, What happens when the TV resolution is changed? Personally I had this issue too but I managed to uninstall/reinstall to make it work successfully

No issue if Xbox resolution is changed to 1080p. Couldn't find a way to change the resolution on the TV (think it's automatic based on the input).

**Comment by TheElixZammuto** [comment]
> > Hi, What happens when the TV resolution is changed? Personally I had this issue too but I managed to uninstall/reinstall to make it work successfully
> 
> No issue if Xbox resolution is changed to 1080p. Couldn't find a way to change the resolution on the TV (think it's automatic based on the input).

Yeah my bad, I was talking about Xbox output instead of the Moonlight resolution setting. Does anyone else can confirm that 1080p  Xboxoutput does work instead of 4k?

**Comment by TheElixZammuto** [comment]
btw I will not able to check this out until next week. Do you prefer to keep this as-is or to rollback to previous version?

**Comment by Ebloin** [comment]
> > > Hi, What happens when the TV resolution is changed? Personally I had this issue too but I managed to uninstall/reinstall to make it work successfully
> > 
> > 
> > No issue if Xbox resolution is changed to 1080p. Couldn't find a way to change the resolution on the TV (think it's automatic based on the input).
> 
> Yeah my bad, I was talking about Xbox output instead of the Moonlight resolution setting. Does anyone else can confirm that 1080p Xboxoutput does work instead of 4k?

Confirm, also for me worked changing the resolution of Xbox to 1080p

**Comment by ReenigneArcher** [comment]
> btw I will not able to check this out until next week. Do you prefer to keep this as-is or to rollback on the store to the previous version?

If it were my project, I probably wouldn't roll back. Maybe just pin the issue so people know that changing xbox resolution can temporarily resolve it.

**Comment by joaopedrosgs** [comment]
I also confirm that changing the resolution of Xbox to 1080p solves the issue
The only problem I have right now is #18

**Comment by TheElixZammuto** [comment]
Does somewant want to try this on 4K on dev mode? https://github.com/TheElixZammuto/moonlight-xbox/actions/runs/1837189118

I've disabled the layout scaler, which maybe can be the cause of the issue (I would love to test this myself, but I don't have a 4K TV nor a capable Xbox)

**Comment by joaopedrosgs** [comment]
Unfortunately, my xbox is on retail mode =/

**Comment by TheElixZammuto** [comment]
I have pushed on the store version 1.8.11 (waiting for approval) , which should disable the layout scaler for the DPI. LEt me know if 4K now works correctly

**Comment by ip0p** [comment]
For me it was working before and now is broken. 
![1646035502418792933694959651232](https://user-images.githubusercontent.com/6025202/155946675-e549beb0-9804-4a7d-9159-5bfa5ec1a2b1.jpg)

**Comment by tsipizic** [comment]
same for me, was working before on 4K resolution and broke on 1.8.11. Tried reinstall and it does not work. Work if I set resolution to 1080p

**Comment by TheElixZammuto** [comment]
@ip0p and @tsipizic, what do you mean by broke? Are you seeing only a quarter of the desktop image? Or the desktop image is using one quarter of your TV?

**Comment by joaopedrosgs** [comment]
I just tested (version 1.8.11.70) and still seeing 1/4 of the desktop image (1/4 of the desktop image fills the entire tv screen)

**Comment by ip0p** [comment]
same as tsipizic. before everything was fine.

**Comment by ReenigneArcher** [comment]
Issue remains for me with 1.8.11.70 as well

**Comment by TheElixZammuto** [comment]
Pushed v1.8.12 which should rollback the modifications and fix the issue

**Comment by Stromduster** [comment]
> Pushed v1.8.12 which should rollback the modifications and fix the issue

I don't experience the issue anymore on 1.8.12 (retail series x). @ReenigneArcher, same on your side?

**Comment by ReenigneArcher** [comment]
> > Pushed v1.8.12 which should rollback the modifications and fix the issue
> 
> I don't experience the issue anymore on 1.8.12 (retail series x). @ReenigneArcher, same on your side?

I still have the issue in 1.8.12.70 retail mode (Xbox One X).

**Comment by joaopedrosgs** [comment]
> I still have the issue in 1.8.12.70 retail mode (Xbox One X).

Me too. And the same workaround still works (disabling 4k in the Xbox configuration menu)

**Comment by expostarv2** [comment]
> > I still have the issue in 1.8.12.70 retail mode (Xbox One X).
> 
> Me too. And the same workaround still works (disabling 4k in the Xbox configuration menu)

Ditto. Also an xbox one x

**Comment by 3ap** [comment]
My problem is quite different: Xbox resolution is 720p, TV resolution is 720p, PC resolution is 720p, selected resolution in application is 720p and picture is only on 1/4 part of the TV screen. Overlay shows that window size is 1280x720. After reverting 258f029ca9dcf80545454e2511c002290a01c702 and 4a6e7e5f49e8064e810d9ab1d0bde5db7f98e1e9 the problem solves.

**Comment by TheElixZammuto** [comment]
> My problem is quite different: Xbox resolution is 720p, TV resolution is 720p, PC resolution is 720p, selected resolution in application is 720p and picture is only on 1/4 part of the TV screen. Overlay shows that window size is 1280x720. After reverting [258f029](https://github.com/TheElixZammuto/moonlight-xbox/commit/258f029ca9dcf80545454e2511c002290a01c702) and [4a6e7e5](https://github.com/TheElixZammuto/moonlight-xbox/commit/4a6e7e5f49e8064e810d9ab1d0bde5db7f98e1e9) the problem solves.

This is probably due to the fact that the CoreWindow is still 1080p in size. I guess that adding a mininum of 1920x1080 for the swapchain size (even in 720p) should work fine

**Comment by Vadhvis** [comment]
Same Issue on 1.9.1 on Xbox Series S (Retail mode) with 1080p Stream resolution, 4k Xbox Resolution

**Comment by TheElixZammuto** [comment]
Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824

On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side

**Comment by Stromduster** [comment]
I tested your build on Xbox Series X dev mode. 

Here is what I noticed : 
- When using Normal resolution scale, 1080p works fine, 4K resulted in an error ("Got status 10060 from Moonlight init"). I supposed it's linked to the crash dump I got. I'll upload it.
- When using 4K for Xbox Series S/Xbox One S, in 1080p, only the top left quarter of the screen is used. And in 4K, same error ("Got status 10060 from Moonlight init")

The dump : https://drive.google.com/file/d/1ijE1brKcUPNlVJR8myiev5Z0gsmmh7bc/view?usp=sharing

**Comment by seskid** [comment]
> I tested your build on Xbox Series X dev mode.
> 
> Here is what I noticed :
> 
> * When using Normal resolution scale, 1080p works fine, 4K resulted in an error ("Got status 10060 from Moonlight init"). I supposed it's linked to the crash dump I got. I'll upload it.
> * When using 4K for Xbox Series S/Xbox One S, in 1080p, only the top left quarter of the screen is used. And in 4K, same error ("Got status 10060 from Moonlight init")
> 
> The dump : https://drive.google.com/file/d/1ijE1brKcUPNlVJR8myiev5Z0gsmmh7bc/view?usp=sharing

Make sure when using a Xbox Series X or Xbox one X , the compoistion scale should always be set to normal.

**Comment by Stromduster** [comment]
> > I tested your build on Xbox Series X dev mode.
> > Here is what I noticed :
> > 
> > * When using Normal resolution scale, 1080p works fine, 4K resulted in an error ("Got status 10060 from Moonlight init"). I supposed it's linked to the crash dump I got. I'll upload it.
> > * When using 4K for Xbox Series S/Xbox One S, in 1080p, only the top left quarter of the screen is used. And in 4K, same error ("Got status 10060 from Moonlight init")
> > 
> > The dump : https://drive.google.com/file/d/1ijE1brKcUPNlVJR8myiev5Z0gsmmh7bc/view?usp=sharing
> 
> Make sure when using a Xbox Series X or Xbox one X , the compoistion scale should always be set to normal.

I suppose it was, I never touched the composition scale.

**Comment by besimple82** [comment]
Is the official Windows Store version same as dev mode version?
I test the dev mode and it display as normal full screen. However, the Windows Store version seems over scan. Such as 1/4 of desktop.
Console: xbox series s with 4k60 TV
PC: win 10 with 2k monitor (main) & 1080 monitor (2nd)
Resolution setting: 1080 ( not sure if it’s 4k scaling in dev mode, I didn’t find the Composition Scale option in setting)

**Comment by seskid** [comment]
> Is the official Windows Store version same as dev mode version? I test the dev mode and it display as normal full screen. However, the Windows Store version seems over scan. Such as 1/4 of desktop. Console: xbox series s with 4k60 TV PC: win 10 with 2k monitor (main) & 1080 monitor (2nd) Resolution setting: 1080 ( not sure if it’s 4k scaling in dev mode, I didn’t find the Composition Scale option in setting)

Was your tv set to 4k and moonlight set to 1080p?

**Comment by besimple82** [comment]
> > Is the official Windows Store version same as dev mode version? I test the dev mode and it display as normal full screen. However, the Windows Store version seems over scan. Such as 1/4 of desktop. Console: xbox series s with 4k60 TV PC: win 10 with 2k monitor (main) & 1080 monitor (2nd) Resolution setting: 1080 ( not sure if it’s 4k scaling in dev mode, I didn’t find the Composition Scale option in setting)
> 
> Was your tv set to 4k and moonlight set to 1080p?

Yes, I did. Interesting thing is that I got a xbox series x today and it shows normal full screen through windows store version of moonlight.
Not sure what happened to series s.

**Comment by seskid** [comment]
Series S uses a 1080p core window and must have the composition scale option set to scale properly for 4k. You can use the assets here 

[](https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824)

 to test this in dev mode.  
Series X core window is 4k and doesnt have this issue.

**Comment by ReenigneArcher** [comment]
I will do my best to test this, but I do not currently have access to my 4k tv. I will report back later.

**Comment by besimple82** [comment]
I've tested it and 4k works perfectly. However, sometime it may crash when connecting to PC.
PC: 2K; XSX: 4K; wired with 100 mbps;

**Comment by ReenigneArcher** [comment]
This is now working fine for me with Xbox One X connected to 1080p TV. I cannot test 4k at this time, but I will close this anyway.

One suggestion/question. Is it possible to detect which type of console and resolution is needed, without the user having to specify it?

**Comment by ericsantosbr** [comment]
I don't know which version I'm currently running, but after installing the app from the provided link in the main repository page, when I try to run a game, it keeps occupying 1/4 of the screen, independently on which resolution I'm running both on console or my PC.

Host Specs:
Ryzen 5 5500
PNY GTX 1660ti - Nvidia driver 527.56
ASRock B450M
Windows 10 22H2
Ultrawide monitor (tried to set it to 1080p but didn't work)

Client specs:
Xbox Series S
1080p LG TV

My TV:
![IMG_20230213_232612.jpg](https://user-images.githubusercontent.com/10171110/218623483-c1dc31d5-dbc7-4577-ab9a-eb51409b5687.jpg)

My TV with a view to my PC monitor:
![IMG_20230213_232622.jpg](https://user-images.githubusercontent.com/10171110/218623497-bf19733b-13ea-4d8d-8bb0-9c07c412084b.jpg)

I tried to see if solutions presented here were working, but couldn't find anything conclusive that worked out for me.

**Comment by ericsantosbr** [comment]
Forgot to turn off 4K upscaling. When I did that, the streaming worked fine. Sorry!

**Comment by joshbirnholz** [comment]
> Forgot to turn off 4K upscaling. When I did that, the streaming worked fine. Sorry!

@ericsantosbr Where did you change that setting? I'm having the same problem. Also on an Xbox One S here. My Xbox is set to output 1080p, Moonlight is set to stream at 1080p, and it still only takes up a quarter of my screen. I'm using the retail version.

**Comment by mkaflowski** [comment]
I have the same problem on Xbox series X. TV and xbox is 4k. When I set moonlight 1080p I get 1/4 of screen and when I set 4k in moonlight I get low res image.

**Comment by HolaSoyGastonGentile** [comment]
Ok, im having the same issue. LG TV 4k. 
Series S, set to 4k i can stream 1440p but the info says its in 4k and it uses the full screen. If i set my xbox to 1440, i only see the top left corner streaming a small window like the GOW picture before, and the info says its in 1440p.  So the info matches the resolution I set, but if i use it on xbox 4k stream 1440p it will take the full screen, if i set the xbox 1440p and stream 1440p it uses a small portion.
Unrelated, I think HDR isnt working for me in the last update 1.16.1, it was working before.
